[package]
name = "yikes-pingora-proxy"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1"
env_logger = "0.11.3"
log = "0.4.21"
pingora = { version = "0.1.0", features = ["proxy", "lb"] }
structopt = "0.3.26"
